### ISSUE TITLE
NameError: name 'sender' is not defined

### ISSUE THREAD

**Issue by Hmtir** [fndh/Anonymous-Telegram-Bot#1]
https://github.com/fndh/Anonymous-Telegram-Bot/blob/9fc73889b92dddda3c951c452c186b169600a4fb/AnonymousForwardBot.py#L185

There is an error in this line:
NameError: name 'sender' is not defined

Have you missed to push some files?

**Comment by fndh** [comment]
Issue due to old name usage in code. Fixed in commit `ea03df6`
