### ISSUE TITLE
Info request: Path in config.txt

### ISSUE THREAD

**Issue by razor2511** [fndh/Anonymous-Telegram-Bot#4]
hi, where do i find the file path requested in config.txt

**Comment by fndh** [comment]
It is the path of the project. I will assign an enhancement tag as it should not be needed.

**Comment by razor2511** [comment]
thanks. couldn't get what i had to do. sorry for that.

**Comment by razor2511** [comment]
sorry again. i get this error.

`C:\Python\Applets\Anonymous-Telegram-Bot-master\AnonymousForwardBot.py:261: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
  updater = Updater(token=my_token)`

bot token, user id and path are correct. Thanks

**Comment by razor2511** [comment]
Otherr request:

I'm trying to host the bot on my vps. After setting the config.txrt and launching the bot through shell, i get this message

`File "AnonymousForwardBot.py", line 145 logger.log(f"getlogs - {e}")`

How can I solve? The system path inserted was (vps ip)"xx.xxx.xxx.xx/path/to/bot/folder".

Thank you!

**Comment by fndh** [comment]
I am working on a fix that removes the path from config.txt. Please be patient.

**Comment by razor2511** [comment]
Thank you.

**Comment by fndh** [comment]
Fixed with commit [1696c31](https://github.com/fndh/Anonymous-Telegram-Bot/commit/1696c315e0819844837122db2869202c7b8d68f1)

**Comment by fndh** [comment]
Fixed with commit [dee234d](https://github.com/fndh/Anonymous-Telegram-Bot/commit/dee234dd9f931b438a9939310e6d54c0fea4999f)
