### ISSUE TITLE
can't start the bot

### ISSUE THREAD

**Issue by kmahsi** [fndh/Anonymous-Telegram-Bot#5]
I've tried running bot with `python AnonymousForwardBot.py` command
But I got this error:
```
  File "AnonymousForwardBot.py", line 146
    logger.log(f"getlogs - {e}")
                              ^
SyntaxError: invalid syntax

```
I'm using python3.5 and I don't know how to solve this error

By removing that line I get another error:

  File "AnonymousForwardBot.py", line 152
    def block_user(update: Update, context: CallbackContext):
      ^
SyntaxError: invalid syntax

**Comment by fndh** [comment]
@kmahsi f-strings are a feature of Python 3.6+. The supported python version is clearly stated in the README file.

**Comment by kmahsi** [comment]
Thanks.
What do you mean of <Your telegram unique identifier here>?
How can I get this?
